import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import Header from "@/app/(saas)/_navigation/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Sidebar } from "@/app/(saas)/_navigation/sidebar/components/sidebar";
import ReactQueryProvider from "@/app/(saas)/_providers/react-query/react-query-provider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai4Safety",
  description: "Generated by NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      {/* <head>
        <Script
          id="cesium-widgets-css"
          strategy="beforeInteractive"
        >{`
          const link = document.createElement('link');
          link.rel = 'stylesheet';
          link.href = '/cesium/Widgets/widgets.css';
          document.head.appendChild(link);
        `}</Script>
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NuqsAdapter>
      <ThemeProvider>
      <ReactQueryProvider>
          {children}
        <Toaster expand />
      </ReactQueryProvider>
      </ThemeProvider>
      </NuqsAdapter>
      </body>
    </html>
  );
}
